name: Go

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: 
          - gh-name: ubuntu-24.04
            artifact-name: linux-amd64
          - gh-name: ubuntu-24.04-arm
            artifact-name: linux-arm64
          - gh-name: macos-latest
            artifact-name: macos-arm64

    runs-on: ${{ matrix.os.gh-name }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.3'
      - name: Build
        run: cd cmd/goimports && go build -v .
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os.artifact-name }}-goimports
          path: cmd/goimports/goimports
